/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreIdentityAbstractParty from './NetCordaCoreIdentityAbstractParty';
import NetCordaCoreIdentityParty from './NetCordaCoreIdentityParty';

/**
 * The BootcampTokenState model module.
 * @module io.generated.model/BootcampTokenState
 * @version 1.0.0
 */
class BootcampTokenState {
    /**
     * Constructs a new <code>BootcampTokenState</code>.
     * @alias module:io.generated.model/BootcampTokenState
     */
    constructor() { 
        
        BootcampTokenState.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BootcampTokenState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/BootcampTokenState} obj Optional instance to populate.
     * @return {module:io.generated.model/BootcampTokenState} The populated <code>BootcampTokenState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BootcampTokenState();

            if (data.hasOwnProperty('issuer')) {
                obj['issuer'] = NetCordaCoreIdentityParty.constructFromObject(data['issuer']);
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = NetCordaCoreIdentityParty.constructFromObject(data['owner']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [NetCordaCoreIdentityAbstractParty]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreIdentityParty} issuer
 */
BootcampTokenState.prototype['issuer'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreIdentityParty} owner
 */
BootcampTokenState.prototype['owner'] = undefined;

/**
 * @member {Number} amount
 */
BootcampTokenState.prototype['amount'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreIdentityAbstractParty>} participants
 */
BootcampTokenState.prototype['participants'] = undefined;






export default BootcampTokenState;

