/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreIdentityParty from './NetCordaCoreIdentityParty';

/**
 * The GeneratedBootcampTokenIssueFlowInitiatorPayload model module.
 * @module io.generated.model/GeneratedBootcampTokenIssueFlowInitiatorPayload
 * @version 1.0.0
 */
class GeneratedBootcampTokenIssueFlowInitiatorPayload {
    /**
     * Constructs a new <code>GeneratedBootcampTokenIssueFlowInitiatorPayload</code>.
     * @alias module:io.generated.model/GeneratedBootcampTokenIssueFlowInitiatorPayload
     * @param owner {module:io.generated.model/NetCordaCoreIdentityParty} 
     * @param amount {Number} 
     */
    constructor(owner, amount) { 
        
        GeneratedBootcampTokenIssueFlowInitiatorPayload.initialize(this, owner, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, owner, amount) { 
        obj['owner'] = owner;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>GeneratedBootcampTokenIssueFlowInitiatorPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/GeneratedBootcampTokenIssueFlowInitiatorPayload} obj Optional instance to populate.
     * @return {module:io.generated.model/GeneratedBootcampTokenIssueFlowInitiatorPayload} The populated <code>GeneratedBootcampTokenIssueFlowInitiatorPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GeneratedBootcampTokenIssueFlowInitiatorPayload();

            if (data.hasOwnProperty('owner')) {
                obj['owner'] = NetCordaCoreIdentityParty.constructFromObject(data['owner']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreIdentityParty} owner
 */
GeneratedBootcampTokenIssueFlowInitiatorPayload.prototype['owner'] = undefined;

/**
 * @member {Number} amount
 */
GeneratedBootcampTokenIssueFlowInitiatorPayload.prototype['amount'] = undefined;






export default GeneratedBootcampTokenIssueFlowInitiatorPayload;

