/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvocationError model module.
 * @module io.generated.model/InvocationError
 * @version 1.0.0
 */
class InvocationError {
    /**
     * Constructs a new <code>InvocationError</code>.
     * Any errors returned by the Progress tracker observable
     * @alias module:io.generated.model/InvocationError
     * @param message {String} the error message
     * @param type {String} the type of error
     */
    constructor(message, type) { 
        
        InvocationError.initialize(this, message, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, type) { 
        obj['message'] = message;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>InvocationError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/InvocationError} obj Optional instance to populate.
     * @return {module:io.generated.model/InvocationError} The populated <code>InvocationError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvocationError();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * the error message
 * @member {String} message
 */
InvocationError.prototype['message'] = undefined;

/**
 * the type of error
 * @member {String} type
 */
InvocationError.prototype['type'] = undefined;






export default InvocationError;

