/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvocationError from './InvocationError';

/**
 * The IoBluebankBraidCordaServerProgressProgressNotification model module.
 * @module io.generated.model/IoBluebankBraidCordaServerProgressProgressNotification
 * @version 1.0.0
 */
class IoBluebankBraidCordaServerProgressProgressNotification {
    /**
     * Constructs a new <code>IoBluebankBraidCordaServerProgressProgressNotification</code>.
     * pet status in the store
     * @alias module:io.generated.model/IoBluebankBraidCordaServerProgressProgressNotification
     * @param complete {Boolean} Indicates if the progress tracker for this flow invocation-id is completed
     */
    constructor(complete) { 
        
        IoBluebankBraidCordaServerProgressProgressNotification.initialize(this, complete);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, complete) { 
        obj['complete'] = complete;
    }

    /**
     * Constructs a <code>IoBluebankBraidCordaServerProgressProgressNotification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/IoBluebankBraidCordaServerProgressProgressNotification} obj Optional instance to populate.
     * @return {module:io.generated.model/IoBluebankBraidCordaServerProgressProgressNotification} The populated <code>IoBluebankBraidCordaServerProgressProgressNotification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoBluebankBraidCordaServerProgressProgressNotification();

            if (data.hasOwnProperty('flowClass')) {
                obj['flowClass'] = ApiClient.convertToType(data['flowClass'], 'String');
            }
            if (data.hasOwnProperty('invocationId')) {
                obj['invocationId'] = ApiClient.convertToType(data['invocationId'], 'String');
            }
            if (data.hasOwnProperty('step')) {
                obj['step'] = ApiClient.convertToType(data['step'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = InvocationError.constructFromObject(data['error']);
            }
            if (data.hasOwnProperty('complete')) {
                obj['complete'] = ApiClient.convertToType(data['complete'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Java class name
 * @member {String} flowClass
 */
IoBluebankBraidCordaServerProgressProgressNotification.prototype['flowClass'] = undefined;

/**
 * The invocation-id header as supplied in the flow initiation post request
 * @member {String} invocationId
 */
IoBluebankBraidCordaServerProgressProgressNotification.prototype['invocationId'] = undefined;

/**
 * The step name as defined by the flow
 * @member {String} step
 */
IoBluebankBraidCordaServerProgressProgressNotification.prototype['step'] = undefined;

/**
 * @member {module:io.generated.model/InvocationError} error
 */
IoBluebankBraidCordaServerProgressProgressNotification.prototype['error'] = undefined;

/**
 * Indicates if the progress tracker for this flow invocation-id is completed
 * @member {Boolean} complete
 */
IoBluebankBraidCordaServerProgressProgressNotification.prototype['complete'] = undefined;






export default IoBluebankBraidCordaServerProgressProgressNotification;

