/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContractsCommandObject from './NetCordaCoreContractsCommandObject';
import NetCordaCoreContractsPrivacySalt from './NetCordaCoreContractsPrivacySalt';
import NetCordaCoreContractsStateRef from './NetCordaCoreContractsStateRef';
import NetCordaCoreContractsTimeWindow from './NetCordaCoreContractsTimeWindow';
import NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState from './NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState';
import NetCordaCoreIdentityParty from './NetCordaCoreIdentityParty';

/**
 * The NetCordaCoreTransactionsWireTransaction model module.
 * @module io.generated.model/NetCordaCoreTransactionsWireTransaction
 * @version 1.0.0
 */
class NetCordaCoreTransactionsWireTransaction {
    /**
     * Constructs a new <code>NetCordaCoreTransactionsWireTransaction</code>.
     * @alias module:io.generated.model/NetCordaCoreTransactionsWireTransaction
     * @param attachments {Array.<String>} 
     * @param inputs {Array.<module:io.generated.model/NetCordaCoreContractsStateRef>} 
     * @param references {Array.<module:io.generated.model/NetCordaCoreContractsStateRef>} 
     * @param outputs {Array.<module:io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState>} 
     * @param commands {Array.<module:io.generated.model/NetCordaCoreContractsCommandObject>} 
     * @param id {String} Base 58 Encoded Secure Hash
     * @param requiredSigningKeys {Array.<String>} 
     * @param groupHashescore {Array.<String>} 
     * @param groupsMerkleRootscore {Object.<String, String>} 
     * @param availableComponentNoncescore {Object.<String, Array.<String>>} 
     * @param availableComponentHashescore {Object.<String, Array.<String>>} 
     */
    constructor(attachments, inputs, references, outputs, commands, id, requiredSigningKeys, groupHashescore, groupsMerkleRootscore, availableComponentNoncescore, availableComponentHashescore) { 
        
        NetCordaCoreTransactionsWireTransaction.initialize(this, attachments, inputs, references, outputs, commands, id, requiredSigningKeys, groupHashescore, groupsMerkleRootscore, availableComponentNoncescore, availableComponentHashescore);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, attachments, inputs, references, outputs, commands, id, requiredSigningKeys, groupHashescore, groupsMerkleRootscore, availableComponentNoncescore, availableComponentHashescore) { 
        obj['attachments'] = attachments;
        obj['inputs'] = inputs;
        obj['references'] = references;
        obj['outputs'] = outputs;
        obj['commands'] = commands;
        obj['id'] = id;
        obj['requiredSigningKeys'] = requiredSigningKeys;
        obj['groupHashes$core'] = groupHashescore;
        obj['groupsMerkleRoots$core'] = groupsMerkleRootscore;
        obj['availableComponentNonces$core'] = availableComponentNoncescore;
        obj['availableComponentHashes$core'] = availableComponentHashescore;
    }

    /**
     * Constructs a <code>NetCordaCoreTransactionsWireTransaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreTransactionsWireTransaction} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreTransactionsWireTransaction} The populated <code>NetCordaCoreTransactionsWireTransaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreTransactionsWireTransaction();

            if (data.hasOwnProperty('privacySalt')) {
                obj['privacySalt'] = NetCordaCoreContractsPrivacySalt.constructFromObject(data['privacySalt']);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], ['String']);
            }
            if (data.hasOwnProperty('inputs')) {
                obj['inputs'] = ApiClient.convertToType(data['inputs'], [NetCordaCoreContractsStateRef]);
            }
            if (data.hasOwnProperty('references')) {
                obj['references'] = ApiClient.convertToType(data['references'], [NetCordaCoreContractsStateRef]);
            }
            if (data.hasOwnProperty('outputs')) {
                obj['outputs'] = ApiClient.convertToType(data['outputs'], [NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState]);
            }
            if (data.hasOwnProperty('commands')) {
                obj['commands'] = ApiClient.convertToType(data['commands'], [NetCordaCoreContractsCommandObject]);
            }
            if (data.hasOwnProperty('notary')) {
                obj['notary'] = NetCordaCoreIdentityParty.constructFromObject(data['notary']);
            }
            if (data.hasOwnProperty('timeWindow')) {
                obj['timeWindow'] = NetCordaCoreContractsTimeWindow.constructFromObject(data['timeWindow']);
            }
            if (data.hasOwnProperty('networkParametersHash')) {
                obj['networkParametersHash'] = ApiClient.convertToType(data['networkParametersHash'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('requiredSigningKeys')) {
                obj['requiredSigningKeys'] = ApiClient.convertToType(data['requiredSigningKeys'], ['String']);
            }
            if (data.hasOwnProperty('groupHashes$core')) {
                obj['groupHashes$core'] = ApiClient.convertToType(data['groupHashes$core'], ['String']);
            }
            if (data.hasOwnProperty('groupsMerkleRoots$core')) {
                obj['groupsMerkleRoots$core'] = ApiClient.convertToType(data['groupsMerkleRoots$core'], {'String': 'String'});
            }
            if (data.hasOwnProperty('availableComponentNonces$core')) {
                obj['availableComponentNonces$core'] = ApiClient.convertToType(data['availableComponentNonces$core'], {'String': ['String']});
            }
            if (data.hasOwnProperty('availableComponentHashes$core')) {
                obj['availableComponentHashes$core'] = ApiClient.convertToType(data['availableComponentHashes$core'], {'String': ['String']});
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreContractsPrivacySalt} privacySalt
 */
NetCordaCoreTransactionsWireTransaction.prototype['privacySalt'] = undefined;

/**
 * @member {Array.<String>} attachments
 */
NetCordaCoreTransactionsWireTransaction.prototype['attachments'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsStateRef>} inputs
 */
NetCordaCoreTransactionsWireTransaction.prototype['inputs'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsStateRef>} references
 */
NetCordaCoreTransactionsWireTransaction.prototype['references'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState>} outputs
 */
NetCordaCoreTransactionsWireTransaction.prototype['outputs'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsCommandObject>} commands
 */
NetCordaCoreTransactionsWireTransaction.prototype['commands'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreIdentityParty} notary
 */
NetCordaCoreTransactionsWireTransaction.prototype['notary'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreContractsTimeWindow} timeWindow
 */
NetCordaCoreTransactionsWireTransaction.prototype['timeWindow'] = undefined;

/**
 * Base 58 Encoded Secure Hash
 * @member {String} networkParametersHash
 */
NetCordaCoreTransactionsWireTransaction.prototype['networkParametersHash'] = undefined;

/**
 * Base 58 Encoded Secure Hash
 * @member {String} id
 */
NetCordaCoreTransactionsWireTransaction.prototype['id'] = undefined;

/**
 * @member {Array.<String>} requiredSigningKeys
 */
NetCordaCoreTransactionsWireTransaction.prototype['requiredSigningKeys'] = undefined;

/**
 * @member {Array.<String>} groupHashes$core
 */
NetCordaCoreTransactionsWireTransaction.prototype['groupHashes$core'] = undefined;

/**
 * @member {Object.<String, String>} groupsMerkleRoots$core
 */
NetCordaCoreTransactionsWireTransaction.prototype['groupsMerkleRoots$core'] = undefined;

/**
 * @member {Object.<String, Array.<String>>} availableComponentNonces$core
 */
NetCordaCoreTransactionsWireTransaction.prototype['availableComponentNonces$core'] = undefined;

/**
 * @member {Object.<String, Array.<String>>} availableComponentHashes$core
 */
NetCordaCoreTransactionsWireTransaction.prototype['availableComponentHashes$core'] = undefined;






export default NetCordaCoreTransactionsWireTransaction;

