/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultPageSpecification model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultPageSpecification
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultPageSpecification {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultPageSpecification</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultPageSpecification
     * @param pageNumber {Number} 
     * @param pageSize {Number} 
     */
    constructor(pageNumber, pageSize) { 
        
        NetCordaCoreNodeServicesVaultPageSpecification.initialize(this, pageNumber, pageSize);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pageNumber, pageSize) { 
        obj['pageNumber'] = pageNumber;
        obj['pageSize'] = pageSize;
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultPageSpecification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultPageSpecification} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultPageSpecification} The populated <code>NetCordaCoreNodeServicesVaultPageSpecification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultPageSpecification();

            if (data.hasOwnProperty('pageNumber')) {
                obj['pageNumber'] = ApiClient.convertToType(data['pageNumber'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} pageNumber
 */
NetCordaCoreNodeServicesVaultPageSpecification.prototype['pageNumber'] = undefined;

/**
 * @member {Number} pageSize
 */
NetCordaCoreNodeServicesVaultPageSpecification.prototype['pageSize'] = undefined;






export default NetCordaCoreNodeServicesVaultPageSpecification;

