/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf
     */
    constructor() { 
        
        NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf} The populated <code>NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf();

            if (data.hasOwnProperty('left')) {
                obj['left'] = ApiClient.convertToType(data['left'], Object);
            }
            if (data.hasOwnProperty('right')) {
                obj['right'] = ApiClient.convertToType(data['right'], Object);
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} left
 */
NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf.prototype['left'] = undefined;

/**
 * @member {Object} right
 */
NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf.prototype['right'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf.OperatorEnum} operator
 */
NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf.prototype['operator'] = undefined;





/**
 * Allowed values for the <code>operator</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf['OperatorEnum'] = {

    /**
     * value: "AND"
     * @const
     */
    "AND": "AND",

    /**
     * value: "OR"
     * @const
     */
    "OR": "OR"
};



export default NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf;

