/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreNodeServicesVaultColumnPredicate from './NetCordaCoreNodeServicesVaultColumnPredicate';
import NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf from './NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf';
import NetCordaCoreNodeServicesVaultColumnPredicateInstant from './NetCordaCoreNodeServicesVaultColumnPredicateInstant';
import NetCordaCoreNodeServicesVaultColumnPredicateLong from './NetCordaCoreNodeServicesVaultColumnPredicateLong';
import NetCordaCoreNodeServicesVaultColumnPredicateObject from './NetCordaCoreNodeServicesVaultColumnPredicateObject';

/**
 * The NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression
     * @extends 
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicate
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateInstant
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateObject
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateLong
     */
    constructor() { 
        NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf.initialize(this);
        NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['operator'] = operator;
        obj['rightLiteral'] = rightLiteral;
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression} The populated <code>NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression();

            ApiClient.constructFromObject(data, obj, '');
            
            NetCordaCoreNodeServicesVaultColumnPredicate.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateInstant.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateObject.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateLong.constructFromObject(data, obj);

            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('rightLiteral')) {
                obj['rightLiteral'] = ApiClient.convertToType(data['rightLiteral'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression.OperatorEnum} operator
 */
NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression.prototype['operator'] = undefined;

/**
 * @member {Array.<Object>} rightLiteral
 */
NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression.prototype['rightLiteral'] = undefined;


// Implement NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf interface:
/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf.OperatorEnum} operator
 */
NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf.prototype['operator'] = undefined;
/**
 * @member {Array.<Object>} rightLiteral
 */
NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf.prototype['rightLiteral'] = undefined;



/**
 * Allowed values for the <code>operator</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression['OperatorEnum'] = {

    /**
     * value: "IN"
     * @const
     */
    "IN": "IN",

    /**
     * value: "NOT_IN"
     * @const
     */
    "NOT_IN": "NOT_IN",

    /**
     * value: "IN_IGNORE_CASE"
     * @const
     */
    "IN_IGNORE_CASE": "IN_IGNORE_CASE",

    /**
     * value: "NOT_IN_IGNORE_CASE"
     * @const
     */
    "NOT_IN_IGNORE_CASE": "NOT_IN_IGNORE_CASE"
};



export default NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression;

