/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContextActorId from './NetCordaCoreContextActorId';
import NetCordaCoreContextAuthServiceId from './NetCordaCoreContextAuthServiceId';

/**
 * The NetCordaCoreContextActor model module.
 * @module io.generated.model/NetCordaCoreContextActor
 * @version 1.0.0
 */
class NetCordaCoreContextActor {
    /**
     * Constructs a new <code>NetCordaCoreContextActor</code>.
     * @alias module:io.generated.model/NetCordaCoreContextActor
     * @param owningLegalIdentity {String} CordaX500Name encoded Party
     */
    constructor(owningLegalIdentity) { 
        
        NetCordaCoreContextActor.initialize(this, owningLegalIdentity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, owningLegalIdentity) { 
        obj['owningLegalIdentity'] = owningLegalIdentity;
    }

    /**
     * Constructs a <code>NetCordaCoreContextActor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContextActor} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContextActor} The populated <code>NetCordaCoreContextActor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContextActor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = NetCordaCoreContextActorId.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('serviceId')) {
                obj['serviceId'] = NetCordaCoreContextAuthServiceId.constructFromObject(data['serviceId']);
            }
            if (data.hasOwnProperty('owningLegalIdentity')) {
                obj['owningLegalIdentity'] = ApiClient.convertToType(data['owningLegalIdentity'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreContextActorId} id
 */
NetCordaCoreContextActor.prototype['id'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreContextAuthServiceId} serviceId
 */
NetCordaCoreContextActor.prototype['serviceId'] = undefined;

/**
 * CordaX500Name encoded Party
 * @member {String} owningLegalIdentity
 */
NetCordaCoreContextActor.prototype['owningLegalIdentity'] = undefined;






export default NetCordaCoreContextActor;

