/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreNodeServicesVaultColumnObjectObject from './NetCordaCoreNodeServicesVaultColumnObjectObject';
import NetCordaCoreNodeServicesVaultCriteriaExpression from './NetCordaCoreNodeServicesVaultCriteriaExpression';
import NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpressionAllOf from './NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpressionAllOf';
import NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean from './NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean';
import NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean from './NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean';

/**
 * The NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression
     * @extends 
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpression
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpressionAllOf
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpression
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean
     */
    constructor() { 
        NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpressionAllOf.initialize(this);
        NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['column'] = column;
        obj['predicate'] = predicate;
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression} The populated <code>NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression();

            ApiClient.constructFromObject(data, obj, '');
            
            NetCordaCoreNodeServicesVaultCriteriaExpression.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpressionAllOf.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultCriteriaExpression.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean.constructFromObject(data, obj);

            if (data.hasOwnProperty('column')) {
                obj['column'] = NetCordaCoreNodeServicesVaultColumnObjectObject.constructFromObject(data['column']);
            }
            if (data.hasOwnProperty('predicate')) {
                obj['predicate'] = ApiClient.convertToType(data['predicate'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnObjectObject} column
 */
NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression.prototype['column'] = undefined;

/**
 * @member {Object} predicate
 */
NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression.prototype['predicate'] = undefined;


// Implement NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpressionAllOf interface:
/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnObjectObject} column
 */
NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpressionAllOf.prototype['column'] = undefined;
/**
 * @member {Object} predicate
 */
NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpressionAllOf.prototype['predicate'] = undefined;




export default NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression;

