/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreUtilitiesByteSequence model module.
 * @module io.generated.model/NetCordaCoreUtilitiesByteSequence
 * @version 1.0.0
 */
class NetCordaCoreUtilitiesByteSequence {
    /**
     * Constructs a new <code>NetCordaCoreUtilitiesByteSequence</code>.
     * @alias module:io.generated.model/NetCordaCoreUtilitiesByteSequence
     * @param offset {Number} 
     * @param size {Number} 
     * @param bytes {File} 
     */
    constructor(offset, size, bytes) { 
        
        NetCordaCoreUtilitiesByteSequence.initialize(this, offset, size, bytes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, offset, size, bytes) { 
        obj['offset'] = offset;
        obj['size'] = size;
        obj['bytes'] = bytes;
    }

    /**
     * Constructs a <code>NetCordaCoreUtilitiesByteSequence</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreUtilitiesByteSequence} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreUtilitiesByteSequence} The populated <code>NetCordaCoreUtilitiesByteSequence</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreUtilitiesByteSequence();

            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('bytes')) {
                obj['bytes'] = ApiClient.convertToType(data['bytes'], File);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} offset
 */
NetCordaCoreUtilitiesByteSequence.prototype['offset'] = undefined;

/**
 * @member {Number} size
 */
NetCordaCoreUtilitiesByteSequence.prototype['size'] = undefined;

/**
 * @member {File} bytes
 */
NetCordaCoreUtilitiesByteSequence.prototype['bytes'] = undefined;






export default NetCordaCoreUtilitiesByteSequence;

