/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreIdentityAbstractParty from './NetCordaCoreIdentityAbstractParty';
import NetCordaCoreNodeServicesVaultConstraintInfo from './NetCordaCoreNodeServicesVaultConstraintInfo';
import NetCordaCoreNodeServicesVaultQueryCriteria from './NetCordaCoreNodeServicesVaultQueryCriteria';
import NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf from './NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf';

/**
 * The NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria
     * @extends 
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteria
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteria
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteria
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteria
     */
    constructor() { 
        NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.initialize(this);
        NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['status'] = status;
        obj['relevancyStatus'] = relevancyStatus;
        obj['constraintTypes'] = constraintTypes;
        obj['constraints'] = constraints;
        obj['externalIds'] = externalIds;
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria} The populated <code>NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria();

            ApiClient.constructFromObject(data, obj, '');
            
            NetCordaCoreNodeServicesVaultQueryCriteria.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultQueryCriteria.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultQueryCriteria.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultQueryCriteria.constructFromObject(data, obj);

            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [NetCordaCoreIdentityAbstractParty]);
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], ['String']);
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], ['String']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('contractStateTypes')) {
                obj['contractStateTypes'] = ApiClient.convertToType(data['contractStateTypes'], ['String']);
            }
            if (data.hasOwnProperty('relevancyStatus')) {
                obj['relevancyStatus'] = ApiClient.convertToType(data['relevancyStatus'], 'String');
            }
            if (data.hasOwnProperty('exactParticipants')) {
                obj['exactParticipants'] = ApiClient.convertToType(data['exactParticipants'], [NetCordaCoreIdentityAbstractParty]);
            }
            if (data.hasOwnProperty('constraintTypes')) {
                obj['constraintTypes'] = ApiClient.convertToType(data['constraintTypes'], ['String']);
            }
            if (data.hasOwnProperty('constraints')) {
                obj['constraints'] = ApiClient.convertToType(data['constraints'], [NetCordaCoreNodeServicesVaultConstraintInfo]);
            }
            if (data.hasOwnProperty('externalIds')) {
                obj['externalIds'] = ApiClient.convertToType(data['externalIds'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreIdentityAbstractParty>} participants
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['participants'] = undefined;

/**
 * @member {Array.<String>} uuid
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['uuid'] = undefined;

/**
 * @member {Array.<String>} externalId
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['externalId'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.StatusEnum} status
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['status'] = undefined;

/**
 * @member {Array.<String>} contractStateTypes
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['contractStateTypes'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.RelevancyStatusEnum} relevancyStatus
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['relevancyStatus'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreIdentityAbstractParty>} exactParticipants
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['exactParticipants'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.ConstraintTypesEnum>} constraintTypes
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['constraintTypes'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreNodeServicesVaultConstraintInfo>} constraints
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['constraints'] = undefined;

/**
 * @member {Array.<String>} externalIds
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria.prototype['externalIds'] = undefined;


// Implement NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf interface:
/**
 * @member {Array.<module:io.generated.model/NetCordaCoreIdentityAbstractParty>} participants
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['participants'] = undefined;
/**
 * @member {Array.<String>} uuid
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['uuid'] = undefined;
/**
 * @member {Array.<String>} externalId
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['externalId'] = undefined;
/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.StatusEnum} status
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['status'] = undefined;
/**
 * @member {Array.<String>} contractStateTypes
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['contractStateTypes'] = undefined;
/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.RelevancyStatusEnum} relevancyStatus
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['relevancyStatus'] = undefined;
/**
 * @member {Array.<module:io.generated.model/NetCordaCoreIdentityAbstractParty>} exactParticipants
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['exactParticipants'] = undefined;
/**
 * @member {Array.<module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.ConstraintTypesEnum>} constraintTypes
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['constraintTypes'] = undefined;
/**
 * @member {Array.<module:io.generated.model/NetCordaCoreNodeServicesVaultConstraintInfo>} constraints
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['constraints'] = undefined;
/**
 * @member {Array.<String>} externalIds
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf.prototype['externalIds'] = undefined;



/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria['StatusEnum'] = {

    /**
     * value: "UNCONSUMED"
     * @const
     */
    "UNCONSUMED": "UNCONSUMED",

    /**
     * value: "CONSUMED"
     * @const
     */
    "CONSUMED": "CONSUMED",

    /**
     * value: "ALL"
     * @const
     */
    "ALL": "ALL"
};


/**
 * Allowed values for the <code>relevancyStatus</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria['RelevancyStatusEnum'] = {

    /**
     * value: "RELEVANT"
     * @const
     */
    "RELEVANT": "RELEVANT",

    /**
     * value: "NOT_RELEVANT"
     * @const
     */
    "NOT_RELEVANT": "NOT_RELEVANT",

    /**
     * value: "ALL"
     * @const
     */
    "ALL": "ALL"
};


/**
 * Allowed values for the <code>constraintTypes</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria['ConstraintTypesEnum'] = {

    /**
     * value: "ALWAYS_ACCEPT"
     * @const
     */
    "ALWAYS_ACCEPT": "ALWAYS_ACCEPT",

    /**
     * value: "HASH"
     * @const
     */
    "HASH": "HASH",

    /**
     * value: "CZ_WHITELISTED"
     * @const
     */
    "CZ_WHITELISTED": "CZ_WHITELISTED",

    /**
     * value: "SIGNATURE"
     * @const
     */
    "SIGNATURE": "SIGNATURE"
};



export default NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria;

