/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultConstraintInfo model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultConstraintInfo
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultConstraintInfo {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultConstraintInfo</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultConstraintInfo
     * @param constraint {Object} 
     */
    constructor(constraint) { 
        
        NetCordaCoreNodeServicesVaultConstraintInfo.initialize(this, constraint);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, constraint) { 
        obj['constraint'] = constraint;
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultConstraintInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultConstraintInfo} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultConstraintInfo} The populated <code>NetCordaCoreNodeServicesVaultConstraintInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultConstraintInfo();

            if (data.hasOwnProperty('constraint')) {
                obj['constraint'] = ApiClient.convertToType(data['constraint'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} constraint
 */
NetCordaCoreNodeServicesVaultConstraintInfo.prototype['constraint'] = undefined;






export default NetCordaCoreNodeServicesVaultConstraintInfo;

