/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreIdentityAbstractParty from './NetCordaCoreIdentityAbstractParty';

/**
 * The NetCordaCoreContractsContractState model module.
 * @module io.generated.model/NetCordaCoreContractsContractState
 * @version 1.0.0
 */
class NetCordaCoreContractsContractState {
    /**
     * Constructs a new <code>NetCordaCoreContractsContractState</code>.
     * @alias module:io.generated.model/NetCordaCoreContractsContractState
     * @param participants {Array.<module:io.generated.model/NetCordaCoreIdentityAbstractParty>} 
     */
    constructor(participants) { 
        
        NetCordaCoreContractsContractState.initialize(this, participants);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, participants) { 
        obj['participants'] = participants;
    }

    /**
     * Constructs a <code>NetCordaCoreContractsContractState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContractsContractState} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContractsContractState} The populated <code>NetCordaCoreContractsContractState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContractsContractState();

            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [NetCordaCoreIdentityAbstractParty]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreIdentityAbstractParty>} participants
 */
NetCordaCoreContractsContractState.prototype['participants'] = undefined;






export default NetCordaCoreContractsContractState;

