/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreIdentityAbstractParty from './NetCordaCoreIdentityAbstractParty';
import NetCordaCoreSchemasPersistentStateRef from './NetCordaCoreSchemasPersistentStateRef';

/**
 * The NetCordaCoreSchemasCommonSchemaV1FungibleState model module.
 * @module io.generated.model/NetCordaCoreSchemasCommonSchemaV1FungibleState
 * @version 1.0.0
 */
class NetCordaCoreSchemasCommonSchemaV1FungibleState {
    /**
     * Constructs a new <code>NetCordaCoreSchemasCommonSchemaV1FungibleState</code>.
     * @alias module:io.generated.model/NetCordaCoreSchemasCommonSchemaV1FungibleState
     * @param quantity {Number} 
     * @param issuerRef {File} 
     */
    constructor(quantity, issuerRef) { 
        
        NetCordaCoreSchemasCommonSchemaV1FungibleState.initialize(this, quantity, issuerRef);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, quantity, issuerRef) { 
        obj['quantity'] = quantity;
        obj['issuerRef'] = issuerRef;
    }

    /**
     * Constructs a <code>NetCordaCoreSchemasCommonSchemaV1FungibleState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreSchemasCommonSchemaV1FungibleState} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreSchemasCommonSchemaV1FungibleState} The populated <code>NetCordaCoreSchemasCommonSchemaV1FungibleState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreSchemasCommonSchemaV1FungibleState();

            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [NetCordaCoreIdentityAbstractParty]);
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = NetCordaCoreIdentityAbstractParty.constructFromObject(data['owner']);
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('issuer')) {
                obj['issuer'] = NetCordaCoreIdentityAbstractParty.constructFromObject(data['issuer']);
            }
            if (data.hasOwnProperty('issuerRef')) {
                obj['issuerRef'] = ApiClient.convertToType(data['issuerRef'], File);
            }
            if (data.hasOwnProperty('stateRef')) {
                obj['stateRef'] = NetCordaCoreSchemasPersistentStateRef.constructFromObject(data['stateRef']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreIdentityAbstractParty>} participants
 */
NetCordaCoreSchemasCommonSchemaV1FungibleState.prototype['participants'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreIdentityAbstractParty} owner
 */
NetCordaCoreSchemasCommonSchemaV1FungibleState.prototype['owner'] = undefined;

/**
 * @member {Number} quantity
 */
NetCordaCoreSchemasCommonSchemaV1FungibleState.prototype['quantity'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreIdentityAbstractParty} issuer
 */
NetCordaCoreSchemasCommonSchemaV1FungibleState.prototype['issuer'] = undefined;

/**
 * @member {File} issuerRef
 */
NetCordaCoreSchemasCommonSchemaV1FungibleState.prototype['issuerRef'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreSchemasPersistentStateRef} stateRef
 */
NetCordaCoreSchemasCommonSchemaV1FungibleState.prototype['stateRef'] = undefined;






export default NetCordaCoreSchemasCommonSchemaV1FungibleState;

