/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContractsContractState from './NetCordaCoreContractsContractState';
import NetCordaCoreIdentityParty from './NetCordaCoreIdentityParty';

/**
 * The NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState model module.
 * @module io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState
 * @version 1.0.0
 */
class NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState {
    /**
     * Constructs a new <code>NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState</code>.
     * @alias module:io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState
     * @param contract {String} 
     */
    constructor(contract) { 
        
        NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState.initialize(this, contract);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contract) { 
        obj['contract'] = contract;
    }

    /**
     * Constructs a <code>NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState} The populated <code>NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState();

            if (data.hasOwnProperty('data')) {
                obj['data'] = NetCordaCoreContractsContractState.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('contract')) {
                obj['contract'] = ApiClient.convertToType(data['contract'], 'String');
            }
            if (data.hasOwnProperty('notary')) {
                obj['notary'] = NetCordaCoreIdentityParty.constructFromObject(data['notary']);
            }
            if (data.hasOwnProperty('encumbrance')) {
                obj['encumbrance'] = ApiClient.convertToType(data['encumbrance'], 'Number');
            }
            if (data.hasOwnProperty('constraint')) {
                obj['constraint'] = ApiClient.convertToType(data['constraint'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreContractsContractState} data
 */
NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState.prototype['data'] = undefined;

/**
 * @member {String} contract
 */
NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState.prototype['contract'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreIdentityParty} notary
 */
NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState.prototype['notary'] = undefined;

/**
 * @member {Number} encumbrance
 */
NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState.prototype['encumbrance'] = undefined;

/**
 * @member {Object} constraint
 */
NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState.prototype['constraint'] = undefined;






export default NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState;

