/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreContractsStateRef model module.
 * @module io.generated.model/NetCordaCoreContractsStateRef
 * @version 1.0.0
 */
class NetCordaCoreContractsStateRef {
    /**
     * Constructs a new <code>NetCordaCoreContractsStateRef</code>.
     * @alias module:io.generated.model/NetCordaCoreContractsStateRef
     * @param txhash {String} Base 58 Encoded Secure Hash
     * @param index {Number} 
     */
    constructor(txhash, index) { 
        
        NetCordaCoreContractsStateRef.initialize(this, txhash, index);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, txhash, index) { 
        obj['txhash'] = txhash;
        obj['index'] = index;
    }

    /**
     * Constructs a <code>NetCordaCoreContractsStateRef</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContractsStateRef} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContractsStateRef} The populated <code>NetCordaCoreContractsStateRef</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContractsStateRef();

            if (data.hasOwnProperty('txhash')) {
                obj['txhash'] = ApiClient.convertToType(data['txhash'], 'String');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Base 58 Encoded Secure Hash
 * @member {String} txhash
 */
NetCordaCoreContractsStateRef.prototype['txhash'] = undefined;

/**
 * @member {Number} index
 */
NetCordaCoreContractsStateRef.prototype['index'] = undefined;






export default NetCordaCoreContractsStateRef;

