/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreUtilitiesOpaqueBytes from './NetCordaCoreUtilitiesOpaqueBytes';

/**
 * The NetCordaCoreTransactionsComponentGroup model module.
 * @module io.generated.model/NetCordaCoreTransactionsComponentGroup
 * @version 1.0.0
 */
class NetCordaCoreTransactionsComponentGroup {
    /**
     * Constructs a new <code>NetCordaCoreTransactionsComponentGroup</code>.
     * @alias module:io.generated.model/NetCordaCoreTransactionsComponentGroup
     * @param groupIndex {Number} 
     * @param components {Array.<module:io.generated.model/NetCordaCoreUtilitiesOpaqueBytes>} 
     */
    constructor(groupIndex, components) { 
        
        NetCordaCoreTransactionsComponentGroup.initialize(this, groupIndex, components);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, groupIndex, components) { 
        obj['groupIndex'] = groupIndex;
        obj['components'] = components;
    }

    /**
     * Constructs a <code>NetCordaCoreTransactionsComponentGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreTransactionsComponentGroup} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreTransactionsComponentGroup} The populated <code>NetCordaCoreTransactionsComponentGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreTransactionsComponentGroup();

            if (data.hasOwnProperty('groupIndex')) {
                obj['groupIndex'] = ApiClient.convertToType(data['groupIndex'], 'Number');
            }
            if (data.hasOwnProperty('components')) {
                obj['components'] = ApiClient.convertToType(data['components'], [NetCordaCoreUtilitiesOpaqueBytes]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} groupIndex
 */
NetCordaCoreTransactionsComponentGroup.prototype['groupIndex'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreUtilitiesOpaqueBytes>} components
 */
NetCordaCoreTransactionsComponentGroup.prototype['components'] = undefined;






export default NetCordaCoreTransactionsComponentGroup;

