/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreContractsAmountTransfer model module.
 * @module io.generated.model/NetCordaCoreContractsAmountTransfer
 * @version 1.0.0
 */
class NetCordaCoreContractsAmountTransfer {
    /**
     * Constructs a new <code>NetCordaCoreContractsAmountTransfer</code>.
     * @alias module:io.generated.model/NetCordaCoreContractsAmountTransfer
     * @param quantityDelta {Number} 
     * @param destination {Object} 
     */
    constructor(quantityDelta, destination) { 
        
        NetCordaCoreContractsAmountTransfer.initialize(this, quantityDelta, destination);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, quantityDelta, destination) { 
        obj['quantityDelta'] = quantityDelta;
        obj['destination'] = destination;
    }

    /**
     * Constructs a <code>NetCordaCoreContractsAmountTransfer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContractsAmountTransfer} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContractsAmountTransfer} The populated <code>NetCordaCoreContractsAmountTransfer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContractsAmountTransfer();

            if (data.hasOwnProperty('quantityDelta')) {
                obj['quantityDelta'] = ApiClient.convertToType(data['quantityDelta'], 'Number');
            }
            if (data.hasOwnProperty('destination')) {
                obj['destination'] = ApiClient.convertToType(data['destination'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} quantityDelta
 */
NetCordaCoreContractsAmountTransfer.prototype['quantityDelta'] = undefined;

/**
 * @member {Object} destination
 */
NetCordaCoreContractsAmountTransfer.prototype['destination'] = undefined;






export default NetCordaCoreContractsAmountTransfer;

