/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf
     */
    constructor() { 
        
        NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf} The populated <code>NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf();

            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('rightLiteral')) {
                obj['rightLiteral'] = ApiClient.convertToType(data['rightLiteral'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf.OperatorEnum} operator
 */
NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf.prototype['operator'] = undefined;

/**
 * @member {Array.<Object>} rightLiteral
 */
NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf.prototype['rightLiteral'] = undefined;





/**
 * Allowed values for the <code>operator</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf['OperatorEnum'] = {

    /**
     * value: "IN"
     * @const
     */
    "IN": "IN",

    /**
     * value: "NOT_IN"
     * @const
     */
    "NOT_IN": "NOT_IN",

    /**
     * value: "IN_IGNORE_CASE"
     * @const
     */
    "IN_IGNORE_CASE": "IN_IGNORE_CASE",

    /**
     * value: "NOT_IN_IGNORE_CASE"
     * @const
     */
    "NOT_IN_IGNORE_CASE": "NOT_IN_IGNORE_CASE"
};



export default NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpressionAllOf;

