/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreUtilitiesId model module.
 * @module io.generated.model/NetCordaCoreUtilitiesId
 * @version 1.0.0
 */
class NetCordaCoreUtilitiesId {
    /**
     * Constructs a new <code>NetCordaCoreUtilitiesId</code>.
     * @alias module:io.generated.model/NetCordaCoreUtilitiesId
     * @param value {Object} 
     * @param timestamp {String} JSR310 encoded time representation of Instant
     */
    constructor(value, timestamp) { 
        
        NetCordaCoreUtilitiesId.initialize(this, value, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value, timestamp) { 
        obj['value'] = value;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>NetCordaCoreUtilitiesId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreUtilitiesId} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreUtilitiesId} The populated <code>NetCordaCoreUtilitiesId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreUtilitiesId();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
            if (data.hasOwnProperty('entityType')) {
                obj['entityType'] = ApiClient.convertToType(data['entityType'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} value
 */
NetCordaCoreUtilitiesId.prototype['value'] = undefined;

/**
 * @member {String} entityType
 */
NetCordaCoreUtilitiesId.prototype['entityType'] = undefined;

/**
 * JSR310 encoded time representation of Instant
 * @member {String} timestamp
 */
NetCordaCoreUtilitiesId.prototype['timestamp'] = undefined;






export default NetCordaCoreUtilitiesId;

