/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf
     */
    constructor() { 
        
        NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf} The populated <code>NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf.TypeEnum} type
 */
NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf['TypeEnum'] = {

    /**
     * value: "COUNT"
     * @const
     */
    "COUNT": "COUNT",

    /**
     * value: "AVG"
     * @const
     */
    "AVG": "AVG",

    /**
     * value: "MIN"
     * @const
     */
    "MIN": "MIN",

    /**
     * value: "MAX"
     * @const
     */
    "MAX": "MAX",

    /**
     * value: "SUM"
     * @const
     */
    "SUM": "SUM"
};



export default NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf;

