/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreContextInvocationOriginPeer model module.
 * @module io.generated.model/NetCordaCoreContextInvocationOriginPeer
 * @version 1.0.0
 */
class NetCordaCoreContextInvocationOriginPeer {
    /**
     * Constructs a new <code>NetCordaCoreContextInvocationOriginPeer</code>.
     * @alias module:io.generated.model/NetCordaCoreContextInvocationOriginPeer
     * @param party {String} CordaX500Name encoded Party
     */
    constructor(party) { 
        
        NetCordaCoreContextInvocationOriginPeer.initialize(this, party);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, party) { 
        obj['party'] = party;
    }

    /**
     * Constructs a <code>NetCordaCoreContextInvocationOriginPeer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContextInvocationOriginPeer} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContextInvocationOriginPeer} The populated <code>NetCordaCoreContextInvocationOriginPeer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContextInvocationOriginPeer();

            if (data.hasOwnProperty('party')) {
                obj['party'] = ApiClient.convertToType(data['party'], 'String');
            }
        }
        return obj;
    }


}

/**
 * CordaX500Name encoded Party
 * @member {String} party
 */
NetCordaCoreContextInvocationOriginPeer.prototype['party'] = undefined;






export default NetCordaCoreContextInvocationOriginPeer;

