/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContractsCommandObject from './NetCordaCoreContractsCommandObject';
import NetCordaCoreContractsContractState from './NetCordaCoreContractsContractState';
import NetCordaCoreContractsStateRef from './NetCordaCoreContractsStateRef';
import NetCordaCoreContractsTimeWindow from './NetCordaCoreContractsTimeWindow';
import NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState from './NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState';
import NetCordaCoreIdentityParty from './NetCordaCoreIdentityParty';
import NetCordaCoreTransactionsComponentGroup from './NetCordaCoreTransactionsComponentGroup';

/**
 * The NetCordaCoreTransactionsTraversableTransaction model module.
 * @module io.generated.model/NetCordaCoreTransactionsTraversableTransaction
 * @version 1.0.0
 */
class NetCordaCoreTransactionsTraversableTransaction {
    /**
     * Constructs a new <code>NetCordaCoreTransactionsTraversableTransaction</code>.
     * @alias module:io.generated.model/NetCordaCoreTransactionsTraversableTransaction
     * @param componentGroups {Array.<module:io.generated.model/NetCordaCoreTransactionsComponentGroup>} 
     * @param attachments {Array.<String>} 
     * @param inputs {Array.<module:io.generated.model/NetCordaCoreContractsStateRef>} 
     * @param references {Array.<module:io.generated.model/NetCordaCoreContractsStateRef>} 
     * @param outputs {Array.<module:io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState>} 
     * @param commands {Array.<module:io.generated.model/NetCordaCoreContractsCommandObject>} 
     * @param outputStates {Array.<module:io.generated.model/NetCordaCoreContractsContractState>} 
     * @param id {String} Base 58 Encoded Secure Hash
     */
    constructor(componentGroups, attachments, inputs, references, outputs, commands, outputStates, id) { 
        
        NetCordaCoreTransactionsTraversableTransaction.initialize(this, componentGroups, attachments, inputs, references, outputs, commands, outputStates, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, componentGroups, attachments, inputs, references, outputs, commands, outputStates, id) { 
        obj['componentGroups'] = componentGroups;
        obj['attachments'] = attachments;
        obj['inputs'] = inputs;
        obj['references'] = references;
        obj['outputs'] = outputs;
        obj['commands'] = commands;
        obj['outputStates'] = outputStates;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>NetCordaCoreTransactionsTraversableTransaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreTransactionsTraversableTransaction} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreTransactionsTraversableTransaction} The populated <code>NetCordaCoreTransactionsTraversableTransaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreTransactionsTraversableTransaction();

            if (data.hasOwnProperty('componentGroups')) {
                obj['componentGroups'] = ApiClient.convertToType(data['componentGroups'], [NetCordaCoreTransactionsComponentGroup]);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], ['String']);
            }
            if (data.hasOwnProperty('inputs')) {
                obj['inputs'] = ApiClient.convertToType(data['inputs'], [NetCordaCoreContractsStateRef]);
            }
            if (data.hasOwnProperty('references')) {
                obj['references'] = ApiClient.convertToType(data['references'], [NetCordaCoreContractsStateRef]);
            }
            if (data.hasOwnProperty('outputs')) {
                obj['outputs'] = ApiClient.convertToType(data['outputs'], [NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState]);
            }
            if (data.hasOwnProperty('commands')) {
                obj['commands'] = ApiClient.convertToType(data['commands'], [NetCordaCoreContractsCommandObject]);
            }
            if (data.hasOwnProperty('notary')) {
                obj['notary'] = NetCordaCoreIdentityParty.constructFromObject(data['notary']);
            }
            if (data.hasOwnProperty('timeWindow')) {
                obj['timeWindow'] = NetCordaCoreContractsTimeWindow.constructFromObject(data['timeWindow']);
            }
            if (data.hasOwnProperty('networkParametersHash')) {
                obj['networkParametersHash'] = ApiClient.convertToType(data['networkParametersHash'], 'String');
            }
            if (data.hasOwnProperty('outputStates')) {
                obj['outputStates'] = ApiClient.convertToType(data['outputStates'], [NetCordaCoreContractsContractState]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreTransactionsComponentGroup>} componentGroups
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['componentGroups'] = undefined;

/**
 * @member {Array.<String>} attachments
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['attachments'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsStateRef>} inputs
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['inputs'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsStateRef>} references
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['references'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState>} outputs
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['outputs'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsCommandObject>} commands
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['commands'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreIdentityParty} notary
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['notary'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreContractsTimeWindow} timeWindow
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['timeWindow'] = undefined;

/**
 * Base 58 Encoded Secure Hash
 * @member {String} networkParametersHash
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['networkParametersHash'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsContractState>} outputStates
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['outputStates'] = undefined;

/**
 * Base 58 Encoded Secure Hash
 * @member {String} id
 */
NetCordaCoreTransactionsTraversableTransaction.prototype['id'] = undefined;






export default NetCordaCoreTransactionsTraversableTransaction;

