/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition
     * @param type {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition.TypeEnum} 
     * @param predicate {Object} 
     */
    constructor(type, predicate) { 
        
        NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition.initialize(this, type, predicate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, predicate) { 
        obj['type'] = type;
        obj['predicate'] = predicate;
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition} The populated <code>NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('predicate')) {
                obj['predicate'] = ApiClient.convertToType(data['predicate'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition.TypeEnum} type
 */
NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition.prototype['type'] = undefined;

/**
 * @member {Object} predicate
 */
NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition.prototype['predicate'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition['TypeEnum'] = {

    /**
     * value: "RECORDED"
     * @const
     */
    "RECORDED": "RECORDED",

    /**
     * value: "CONSUMED"
     * @const
     */
    "CONSUMED": "CONSUMED"
};



export default NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition;

