/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreNodeNodeInfo from './NetCordaCoreNodeNodeInfo';

/**
 * The NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded model module.
 * @module io.generated.model/NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded
     */
    constructor() { 
        
        NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded} The populated <code>NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded();

            if (data.hasOwnProperty('node')) {
                obj['node'] = NetCordaCoreNodeNodeInfo.constructFromObject(data['node']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreNodeNodeInfo} node
 */
NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded.prototype['node'] = undefined;






export default NetCordaCoreNodeServicesNetworkMapCacheMapChangeAdded;

