/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContractsContractState from './NetCordaCoreContractsContractState';
import NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState from './NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState';
import NetCordaCoreIdentityParty from './NetCordaCoreIdentityParty';

/**
 * The NetCordaCoreTransactionsBaseTransaction model module.
 * @module io.generated.model/NetCordaCoreTransactionsBaseTransaction
 * @version 1.0.0
 */
class NetCordaCoreTransactionsBaseTransaction {
    /**
     * Constructs a new <code>NetCordaCoreTransactionsBaseTransaction</code>.
     * @alias module:io.generated.model/NetCordaCoreTransactionsBaseTransaction
     * @param inputs {Array.<Object>} 
     * @param references {Array.<Object>} 
     * @param outputs {Array.<module:io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState>} 
     * @param outputStates {Array.<module:io.generated.model/NetCordaCoreContractsContractState>} 
     * @param id {String} Base 58 Encoded Secure Hash
     */
    constructor(inputs, references, outputs, outputStates, id) { 
        
        NetCordaCoreTransactionsBaseTransaction.initialize(this, inputs, references, outputs, outputStates, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, inputs, references, outputs, outputStates, id) { 
        obj['inputs'] = inputs;
        obj['references'] = references;
        obj['outputs'] = outputs;
        obj['outputStates'] = outputStates;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>NetCordaCoreTransactionsBaseTransaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreTransactionsBaseTransaction} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreTransactionsBaseTransaction} The populated <code>NetCordaCoreTransactionsBaseTransaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreTransactionsBaseTransaction();

            if (data.hasOwnProperty('inputs')) {
                obj['inputs'] = ApiClient.convertToType(data['inputs'], [Object]);
            }
            if (data.hasOwnProperty('references')) {
                obj['references'] = ApiClient.convertToType(data['references'], [Object]);
            }
            if (data.hasOwnProperty('notary')) {
                obj['notary'] = NetCordaCoreIdentityParty.constructFromObject(data['notary']);
            }
            if (data.hasOwnProperty('outputs')) {
                obj['outputs'] = ApiClient.convertToType(data['outputs'], [NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState]);
            }
            if (data.hasOwnProperty('outputStates')) {
                obj['outputStates'] = ApiClient.convertToType(data['outputStates'], [NetCordaCoreContractsContractState]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Object>} inputs
 */
NetCordaCoreTransactionsBaseTransaction.prototype['inputs'] = undefined;

/**
 * @member {Array.<Object>} references
 */
NetCordaCoreTransactionsBaseTransaction.prototype['references'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreIdentityParty} notary
 */
NetCordaCoreTransactionsBaseTransaction.prototype['notary'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState>} outputs
 */
NetCordaCoreTransactionsBaseTransaction.prototype['outputs'] = undefined;

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreContractsContractState>} outputStates
 */
NetCordaCoreTransactionsBaseTransaction.prototype['outputStates'] = undefined;

/**
 * Base 58 Encoded Secure Hash
 * @member {String} id
 */
NetCordaCoreTransactionsBaseTransaction.prototype['id'] = undefined;






export default NetCordaCoreTransactionsBaseTransaction;

