/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreCryptoPartialMerkleTree from './NetCordaCoreCryptoPartialMerkleTree';
import NetCordaCoreCryptoSignatureMetadata from './NetCordaCoreCryptoSignatureMetadata';

/**
 * The NetCordaCoreCryptoTransactionSignature model module.
 * @module io.generated.model/NetCordaCoreCryptoTransactionSignature
 * @version 1.0.0
 */
class NetCordaCoreCryptoTransactionSignature {
    /**
     * Constructs a new <code>NetCordaCoreCryptoTransactionSignature</code>.
     * @alias module:io.generated.model/NetCordaCoreCryptoTransactionSignature
     * @param bytes {File} 
     * @param by {String} Base 58 Encoded Public Key
     */
    constructor(bytes, by) { 
        
        NetCordaCoreCryptoTransactionSignature.initialize(this, bytes, by);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, bytes, by) { 
        obj['bytes'] = bytes;
        obj['by'] = by;
    }

    /**
     * Constructs a <code>NetCordaCoreCryptoTransactionSignature</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreCryptoTransactionSignature} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreCryptoTransactionSignature} The populated <code>NetCordaCoreCryptoTransactionSignature</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreCryptoTransactionSignature();

            if (data.hasOwnProperty('bytes')) {
                obj['bytes'] = ApiClient.convertToType(data['bytes'], File);
            }
            if (data.hasOwnProperty('by')) {
                obj['by'] = ApiClient.convertToType(data['by'], 'String');
            }
            if (data.hasOwnProperty('signatureMetadata')) {
                obj['signatureMetadata'] = NetCordaCoreCryptoSignatureMetadata.constructFromObject(data['signatureMetadata']);
            }
            if (data.hasOwnProperty('partialMerkleTree')) {
                obj['partialMerkleTree'] = NetCordaCoreCryptoPartialMerkleTree.constructFromObject(data['partialMerkleTree']);
            }
        }
        return obj;
    }


}

/**
 * @member {File} bytes
 */
NetCordaCoreCryptoTransactionSignature.prototype['bytes'] = undefined;

/**
 * Base 58 Encoded Public Key
 * @member {String} by
 */
NetCordaCoreCryptoTransactionSignature.prototype['by'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreCryptoSignatureMetadata} signatureMetadata
 */
NetCordaCoreCryptoTransactionSignature.prototype['signatureMetadata'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreCryptoPartialMerkleTree} partialMerkleTree
 */
NetCordaCoreCryptoTransactionSignature.prototype['partialMerkleTree'] = undefined;






export default NetCordaCoreCryptoTransactionSignature;

