/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf
     */
    constructor() { 
        
        NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf} The populated <code>NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf();

            if (data.hasOwnProperty('expression')) {
                obj['expression'] = ApiClient.convertToType(data['expression'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} expression
 */
NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf.prototype['expression'] = undefined;






export default NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf;

