/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContextActor from './NetCordaCoreContextActor';

/**
 * The NetCordaCoreContextInvocationOriginRPC model module.
 * @module io.generated.model/NetCordaCoreContextInvocationOriginRPC
 * @version 1.0.0
 */
class NetCordaCoreContextInvocationOriginRPC {
    /**
     * Constructs a new <code>NetCordaCoreContextInvocationOriginRPC</code>.
     * @alias module:io.generated.model/NetCordaCoreContextInvocationOriginRPC
     */
    constructor() { 
        
        NetCordaCoreContextInvocationOriginRPC.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreContextInvocationOriginRPC</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContextInvocationOriginRPC} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContextInvocationOriginRPC} The populated <code>NetCordaCoreContextInvocationOriginRPC</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContextInvocationOriginRPC();

            if (data.hasOwnProperty('actor')) {
                obj['actor'] = NetCordaCoreContextActor.constructFromObject(data['actor']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreContextActor} actor
 */
NetCordaCoreContextInvocationOriginRPC.prototype['actor'] = undefined;






export default NetCordaCoreContextInvocationOriginRPC;

