/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition
     */
    constructor() { 
        
        NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition} The populated <code>NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition();

            if (data.hasOwnProperty('a')) {
                obj['a'] = ApiClient.convertToType(data['a'], Object);
            }
            if (data.hasOwnProperty('b')) {
                obj['b'] = ApiClient.convertToType(data['b'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} a
 */
NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition.prototype['a'] = undefined;

/**
 * @member {Object} b
 */
NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition.prototype['b'] = undefined;






export default NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAndComposition;

