/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContextActor from './NetCordaCoreContextActor';
import NetCordaCoreContextTrace from './NetCordaCoreContextTrace';

/**
 * The NetCordaCoreContextInvocationContext model module.
 * @module io.generated.model/NetCordaCoreContextInvocationContext
 * @version 1.0.0
 */
class NetCordaCoreContextInvocationContext {
    /**
     * Constructs a new <code>NetCordaCoreContextInvocationContext</code>.
     * @alias module:io.generated.model/NetCordaCoreContextInvocationContext
     */
    constructor() { 
        
        NetCordaCoreContextInvocationContext.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreContextInvocationContext</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContextInvocationContext} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContextInvocationContext} The populated <code>NetCordaCoreContextInvocationContext</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContextInvocationContext();

            if (data.hasOwnProperty('origin')) {
                obj['origin'] = ApiClient.convertToType(data['origin'], Object);
            }
            if (data.hasOwnProperty('trace')) {
                obj['trace'] = NetCordaCoreContextTrace.constructFromObject(data['trace']);
            }
            if (data.hasOwnProperty('actor')) {
                obj['actor'] = NetCordaCoreContextActor.constructFromObject(data['actor']);
            }
            if (data.hasOwnProperty('externalTrace')) {
                obj['externalTrace'] = NetCordaCoreContextTrace.constructFromObject(data['externalTrace']);
            }
            if (data.hasOwnProperty('impersonatedActor')) {
                obj['impersonatedActor'] = NetCordaCoreContextActor.constructFromObject(data['impersonatedActor']);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} origin
 */
NetCordaCoreContextInvocationContext.prototype['origin'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreContextTrace} trace
 */
NetCordaCoreContextInvocationContext.prototype['trace'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreContextActor} actor
 */
NetCordaCoreContextInvocationContext.prototype['actor'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreContextTrace} externalTrace
 */
NetCordaCoreContextInvocationContext.prototype['externalTrace'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreContextActor} impersonatedActor
 */
NetCordaCoreContextInvocationContext.prototype['impersonatedActor'] = undefined;






export default NetCordaCoreContextInvocationContext;

