/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf from './NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf';
import NetCordaCoreNodeServicesVaultColumnPredicateInstant from './NetCordaCoreNodeServicesVaultColumnPredicateInstant';
import NetCordaCoreNodeServicesVaultColumnPredicateLong from './NetCordaCoreNodeServicesVaultColumnPredicateLong';
import NetCordaCoreNodeServicesVaultColumnPredicateObject from './NetCordaCoreNodeServicesVaultColumnPredicateObject';

/**
 * The NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction
     * @extends 
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateInstant
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateInstant
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateObject
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateObject
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateLong
     * @implements module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateLong
     */
    constructor() { 
        NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf.initialize(this);
        NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction} The populated <code>NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction();

            ApiClient.constructFromObject(data, obj, '');
            
            NetCordaCoreNodeServicesVaultColumnPredicateInstant.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateInstant.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateObject.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateObject.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateLong.constructFromObject(data, obj);
            NetCordaCoreNodeServicesVaultColumnPredicateLong.constructFromObject(data, obj);

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction.TypeEnum} type
 */
NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction.prototype['type'] = undefined;


// Implement NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf interface:
/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf.TypeEnum} type
 */
NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf.prototype['type'] = undefined;



/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction['TypeEnum'] = {

    /**
     * value: "COUNT"
     * @const
     */
    "COUNT": "COUNT",

    /**
     * value: "AVG"
     * @const
     */
    "AVG": "AVG",

    /**
     * value: "MIN"
     * @const
     */
    "MIN": "MIN",

    /**
     * value: "MAX"
     * @const
     */
    "MAX": "MAX",

    /**
     * value: "SUM"
     * @const
     */
    "SUM": "SUM"
};



export default NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction;

