/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition
     * @param type {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition.TypeEnum} 
     * @param lockIds {Array.<String>} 
     */
    constructor(type, lockIds) { 
        
        NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition.initialize(this, type, lockIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, lockIds) { 
        obj['type'] = type;
        obj['lockIds'] = lockIds;
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition} The populated <code>NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('lockIds')) {
                obj['lockIds'] = ApiClient.convertToType(data['lockIds'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition.TypeEnum} type
 */
NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition.prototype['type'] = undefined;

/**
 * @member {Array.<String>} lockIds
 */
NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition.prototype['lockIds'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition['TypeEnum'] = {

    /**
     * value: "UNLOCKED_ONLY"
     * @const
     */
    "UNLOCKED_ONLY": "UNLOCKED_ONLY",

    /**
     * value: "LOCKED_ONLY"
     * @const
     */
    "LOCKED_ONLY": "LOCKED_ONLY",

    /**
     * value: "SPECIFIED"
     * @const
     */
    "SPECIFIED": "SPECIFIED",

    /**
     * value: "UNLOCKED_AND_SPECIFIED"
     * @const
     */
    "UNLOCKED_AND_SPECIFIED": "UNLOCKED_AND_SPECIFIED"
};



export default NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition;

