/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContractsStateRef from './NetCordaCoreContractsStateRef';

/**
 * The NetCordaCoreContractsScheduledStateRef model module.
 * @module io.generated.model/NetCordaCoreContractsScheduledStateRef
 * @version 1.0.0
 */
class NetCordaCoreContractsScheduledStateRef {
    /**
     * Constructs a new <code>NetCordaCoreContractsScheduledStateRef</code>.
     * @alias module:io.generated.model/NetCordaCoreContractsScheduledStateRef
     * @param scheduledAt {String} JSR310 encoded time representation of Instant
     */
    constructor(scheduledAt) { 
        
        NetCordaCoreContractsScheduledStateRef.initialize(this, scheduledAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, scheduledAt) { 
        obj['scheduledAt'] = scheduledAt;
    }

    /**
     * Constructs a <code>NetCordaCoreContractsScheduledStateRef</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContractsScheduledStateRef} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContractsScheduledStateRef} The populated <code>NetCordaCoreContractsScheduledStateRef</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContractsScheduledStateRef();

            if (data.hasOwnProperty('ref')) {
                obj['ref'] = NetCordaCoreContractsStateRef.constructFromObject(data['ref']);
            }
            if (data.hasOwnProperty('scheduledAt')) {
                obj['scheduledAt'] = ApiClient.convertToType(data['scheduledAt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreContractsStateRef} ref
 */
NetCordaCoreContractsScheduledStateRef.prototype['ref'] = undefined;

/**
 * JSR310 encoded time representation of Instant
 * @member {String} scheduledAt
 */
NetCordaCoreContractsScheduledStateRef.prototype['scheduledAt'] = undefined;






export default NetCordaCoreContractsScheduledStateRef;

