/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreIdentityAbstractParty from './NetCordaCoreIdentityAbstractParty';
import NetCordaCoreSchemasPersistentStateRef from './NetCordaCoreSchemasPersistentStateRef';

/**
 * The NetCordaCoreSchemasCommonSchemaV1LinearState model module.
 * @module io.generated.model/NetCordaCoreSchemasCommonSchemaV1LinearState
 * @version 1.0.0
 */
class NetCordaCoreSchemasCommonSchemaV1LinearState {
    /**
     * Constructs a new <code>NetCordaCoreSchemasCommonSchemaV1LinearState</code>.
     * @alias module:io.generated.model/NetCordaCoreSchemasCommonSchemaV1LinearState
     * @param uuid {String} 
     */
    constructor(uuid) { 
        
        NetCordaCoreSchemasCommonSchemaV1LinearState.initialize(this, uuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid) { 
        obj['uuid'] = uuid;
    }

    /**
     * Constructs a <code>NetCordaCoreSchemasCommonSchemaV1LinearState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreSchemasCommonSchemaV1LinearState} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreSchemasCommonSchemaV1LinearState} The populated <code>NetCordaCoreSchemasCommonSchemaV1LinearState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreSchemasCommonSchemaV1LinearState();

            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [NetCordaCoreIdentityAbstractParty]);
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('stateRef')) {
                obj['stateRef'] = NetCordaCoreSchemasPersistentStateRef.constructFromObject(data['stateRef']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:io.generated.model/NetCordaCoreIdentityAbstractParty>} participants
 */
NetCordaCoreSchemasCommonSchemaV1LinearState.prototype['participants'] = undefined;

/**
 * @member {String} externalId
 */
NetCordaCoreSchemasCommonSchemaV1LinearState.prototype['externalId'] = undefined;

/**
 * @member {String} uuid
 */
NetCordaCoreSchemasCommonSchemaV1LinearState.prototype['uuid'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreSchemasPersistentStateRef} stateRef
 */
NetCordaCoreSchemasCommonSchemaV1LinearState.prototype['stateRef'] = undefined;






export default NetCordaCoreSchemasCommonSchemaV1LinearState;

