/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreCryptoSignatureMetadata model module.
 * @module io.generated.model/NetCordaCoreCryptoSignatureMetadata
 * @version 1.0.0
 */
class NetCordaCoreCryptoSignatureMetadata {
    /**
     * Constructs a new <code>NetCordaCoreCryptoSignatureMetadata</code>.
     * @alias module:io.generated.model/NetCordaCoreCryptoSignatureMetadata
     * @param platformVersion {Number} 
     * @param schemeNumberID {Number} 
     */
    constructor(platformVersion, schemeNumberID) { 
        
        NetCordaCoreCryptoSignatureMetadata.initialize(this, platformVersion, schemeNumberID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, platformVersion, schemeNumberID) { 
        obj['platformVersion'] = platformVersion;
        obj['schemeNumberID'] = schemeNumberID;
    }

    /**
     * Constructs a <code>NetCordaCoreCryptoSignatureMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreCryptoSignatureMetadata} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreCryptoSignatureMetadata} The populated <code>NetCordaCoreCryptoSignatureMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreCryptoSignatureMetadata();

            if (data.hasOwnProperty('platformVersion')) {
                obj['platformVersion'] = ApiClient.convertToType(data['platformVersion'], 'Number');
            }
            if (data.hasOwnProperty('schemeNumberID')) {
                obj['schemeNumberID'] = ApiClient.convertToType(data['schemeNumberID'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} platformVersion
 */
NetCordaCoreCryptoSignatureMetadata.prototype['platformVersion'] = undefined;

/**
 * @member {Number} schemeNumberID
 */
NetCordaCoreCryptoSignatureMetadata.prototype['schemeNumberID'] = undefined;






export default NetCordaCoreCryptoSignatureMetadata;

