/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVault model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVault
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVault {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVault</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVault
     * @param states {Object} 
     */
    constructor(states) { 
        
        NetCordaCoreNodeServicesVault.initialize(this, states);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, states) { 
        obj['states'] = states;
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVault</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVault} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVault} The populated <code>NetCordaCoreNodeServicesVault</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVault();

            if (data.hasOwnProperty('states')) {
                obj['states'] = ApiClient.convertToType(data['states'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} states
 */
NetCordaCoreNodeServicesVault.prototype['states'] = undefined;






export default NetCordaCoreNodeServicesVault;

