/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf model module.
 * @module io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf
 * @version 1.0.0
 */
class NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf {
    /**
     * Constructs a new <code>NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf</code>.
     * @alias module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf
     */
    constructor() { 
        
        NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf} The populated <code>NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf();

            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('rightLiteral')) {
                obj['rightLiteral'] = ApiClient.convertToType(data['rightLiteral'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf.OperatorEnum} operator
 */
NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf.prototype['operator'] = undefined;

/**
 * @member {String} rightLiteral
 */
NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf.prototype['rightLiteral'] = undefined;





/**
 * Allowed values for the <code>operator</code> property.
 * @enum {String}
 * @readonly
 */
NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf['OperatorEnum'] = {

    /**
     * value: "LIKE"
     * @const
     */
    "LIKE": "LIKE",

    /**
     * value: "NOT_LIKE"
     * @const
     */
    "NOT_LIKE": "NOT_LIKE",

    /**
     * value: "LIKE_IGNORE_CASE"
     * @const
     */
    "LIKE_IGNORE_CASE": "LIKE_IGNORE_CASE",

    /**
     * value: "NOT_LIKE_IGNORE_CASE"
     * @const
     */
    "NOT_LIKE_IGNORE_CASE": "NOT_LIKE_IGNORE_CASE"
};



export default NetCordaCoreNodeServicesVaultColumnPredicateLikenessAllOf;

