/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContextTraceInvocationId from './NetCordaCoreContextTraceInvocationId';
import NetCordaCoreContextTraceSessionId from './NetCordaCoreContextTraceSessionId';

/**
 * The NetCordaCoreContextTrace model module.
 * @module io.generated.model/NetCordaCoreContextTrace
 * @version 1.0.0
 */
class NetCordaCoreContextTrace {
    /**
     * Constructs a new <code>NetCordaCoreContextTrace</code>.
     * @alias module:io.generated.model/NetCordaCoreContextTrace
     */
    constructor() { 
        
        NetCordaCoreContextTrace.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetCordaCoreContextTrace</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContextTrace} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContextTrace} The populated <code>NetCordaCoreContextTrace</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContextTrace();

            if (data.hasOwnProperty('invocationId')) {
                obj['invocationId'] = NetCordaCoreContextTraceInvocationId.constructFromObject(data['invocationId']);
            }
            if (data.hasOwnProperty('sessionId')) {
                obj['sessionId'] = NetCordaCoreContextTraceSessionId.constructFromObject(data['sessionId']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreContextTraceInvocationId} invocationId
 */
NetCordaCoreContextTrace.prototype['invocationId'] = undefined;

/**
 * @member {module:io.generated.model/NetCordaCoreContextTraceSessionId} sessionId
 */
NetCordaCoreContextTrace.prototype['sessionId'] = undefined;






export default NetCordaCoreContextTrace;

