/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreUtilitiesOpaqueBytes from './NetCordaCoreUtilitiesOpaqueBytes';

/**
 * The NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent model module.
 * @module io.generated.model/NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent
 * @version 1.0.0
 */
class NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent {
    /**
     * Constructs a new <code>NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent</code>.
     * @alias module:io.generated.model/NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent
     * @param nonce {String} Base 58 Encoded Secure Hash
     */
    constructor(nonce) { 
        
        NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent.initialize(this, nonce);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nonce) { 
        obj['nonce'] = nonce;
    }

    /**
     * Constructs a <code>NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent} The populated <code>NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent();

            if (data.hasOwnProperty('component')) {
                obj['component'] = NetCordaCoreUtilitiesOpaqueBytes.constructFromObject(data['component']);
            }
            if (data.hasOwnProperty('nonce')) {
                obj['nonce'] = ApiClient.convertToType(data['nonce'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreUtilitiesOpaqueBytes} component
 */
NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent.prototype['component'] = undefined;

/**
 * Base 58 Encoded Secure Hash
 * @member {String} nonce
 */
NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent.prototype['nonce'] = undefined;






export default NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent;

