/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NetCordaCoreTransactionsSignedTransaction', function() {
    it('should create an instance of NetCordaCoreTransactionsSignedTransaction', function() {
      // uncomment below and update the code to test NetCordaCoreTransactionsSignedTransaction
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be.a(OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction);
    });

    it('should have the property txBits (base name: "txBits")', function() {
      // uncomment below and update the code to test the property txBits
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property sigs (base name: "sigs")', function() {
      // uncomment below and update the code to test the property sigs
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tx (base name: "tx")', function() {
      // uncomment below and update the code to test the property tx
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property coreTransaction (base name: "coreTransaction")', function() {
      // uncomment below and update the code to test the property coreTransaction
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property inputs (base name: "inputs")', function() {
      // uncomment below and update the code to test the property inputs
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property references (base name: "references")', function() {
      // uncomment below and update the code to test the property references
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property notary (base name: "notary")', function() {
      // uncomment below and update the code to test the property notary
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property networkParametersHash (base name: "networkParametersHash")', function() {
      // uncomment below and update the code to test the property networkParametersHash
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property notaryChangeTransaction (base name: "notaryChangeTransaction")', function() {
      // uncomment below and update the code to test the property notaryChangeTransaction
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

    it('should have the property missingSigners (base name: "missingSigners")', function() {
      // uncomment below and update the code to test the property missingSigners
      //var instane = new OpenapiJsClient.NetCordaCoreTransactionsSignedTransaction();
      //expect(instance).to.be();
    });

  });

}));
