/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState', function() {
    it('should create an instance of NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState', function() {
      // uncomment below and update the code to test NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState
      //var instane = new OpenapiJsClient.NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState();
      //expect(instance).to.be.a(OpenapiJsClient.NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState);
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new OpenapiJsClient.NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState();
      //expect(instance).to.be();
    });

    it('should have the property ref (base name: "ref")', function() {
      // uncomment below and update the code to test the property ref
      //var instane = new OpenapiJsClient.NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState();
      //expect(instance).to.be();
    });

  });

}));
