/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria', function() {
    it('should create an instance of NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria', function() {
      // uncomment below and update the code to test NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria();
      //expect(instance).to.be.a(OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria);
    });

    it('should have the property uploaderCondition (base name: "uploaderCondition")', function() {
      // uncomment below and update the code to test the property uploaderCondition
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria();
      //expect(instance).to.be();
    });

    it('should have the property filenameCondition (base name: "filenameCondition")', function() {
      // uncomment below and update the code to test the property filenameCondition
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria();
      //expect(instance).to.be();
    });

    it('should have the property uploadDateCondition (base name: "uploadDateCondition")', function() {
      // uncomment below and update the code to test the property uploadDateCondition
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria();
      //expect(instance).to.be();
    });

    it('should have the property contractClassNamesCondition (base name: "contractClassNamesCondition")', function() {
      // uncomment below and update the code to test the property contractClassNamesCondition
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria();
      //expect(instance).to.be();
    });

    it('should have the property signersCondition (base name: "signersCondition")', function() {
      // uncomment below and update the code to test the property signersCondition
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria();
      //expect(instance).to.be();
    });

    it('should have the property isSignedCondition (base name: "isSignedCondition")', function() {
      // uncomment below and update the code to test the property isSignedCondition
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria();
      //expect(instance).to.be();
    });

    it('should have the property versionCondition (base name: "versionCondition")', function() {
      // uncomment below and update the code to test the property versionCondition
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria();
      //expect(instance).to.be();
    });

  });

}));
