/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NetCordaCoreNodeServicesVaultStateMetadata', function() {
    it('should create an instance of NetCordaCoreNodeServicesVaultStateMetadata', function() {
      // uncomment below and update the code to test NetCordaCoreNodeServicesVaultStateMetadata
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be.a(OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata);
    });

    it('should have the property ref (base name: "ref")', function() {
      // uncomment below and update the code to test the property ref
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

    it('should have the property contractStateClassName (base name: "contractStateClassName")', function() {
      // uncomment below and update the code to test the property contractStateClassName
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

    it('should have the property recordedTime (base name: "recordedTime")', function() {
      // uncomment below and update the code to test the property recordedTime
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

    it('should have the property consumedTime (base name: "consumedTime")', function() {
      // uncomment below and update the code to test the property consumedTime
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

    it('should have the property notary (base name: "notary")', function() {
      // uncomment below and update the code to test the property notary
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

    it('should have the property lockId (base name: "lockId")', function() {
      // uncomment below and update the code to test the property lockId
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

    it('should have the property lockUpdateTime (base name: "lockUpdateTime")', function() {
      // uncomment below and update the code to test the property lockUpdateTime
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

    it('should have the property relevancyStatus (base name: "relevancyStatus")', function() {
      // uncomment below and update the code to test the property relevancyStatus
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

    it('should have the property constraintInfo (base name: "constraintInfo")', function() {
      // uncomment below and update the code to test the property constraintInfo
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultStateMetadata();
      //expect(instance).to.be();
    });

  });

}));
