/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.NetCordaCoreNodeServicesVaultUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NetCordaCoreNodeServicesVaultUpdate', function() {
    it('should create an instance of NetCordaCoreNodeServicesVaultUpdate', function() {
      // uncomment below and update the code to test NetCordaCoreNodeServicesVaultUpdate
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultUpdate();
      //expect(instance).to.be.a(OpenapiJsClient.NetCordaCoreNodeServicesVaultUpdate);
    });

    it('should have the property consumed (base name: "consumed")', function() {
      // uncomment below and update the code to test the property consumed
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultUpdate();
      //expect(instance).to.be();
    });

    it('should have the property produced (base name: "produced")', function() {
      // uncomment below and update the code to test the property produced
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultUpdate();
      //expect(instance).to.be();
    });

    it('should have the property flowId (base name: "flowId")', function() {
      // uncomment below and update the code to test the property flowId
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultUpdate();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultUpdate();
      //expect(instance).to.be();
    });

    it('should have the property references (base name: "references")', function() {
      // uncomment below and update the code to test the property references
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultUpdate();
      //expect(instance).to.be();
    });

    it('should have the property empty (base name: "empty")', function() {
      // uncomment below and update the code to test the property empty
      //var instane = new OpenapiJsClient.NetCordaCoreNodeServicesVaultUpdate();
      //expect(instance).to.be();
    });

  });

}));
